services:
  app:
    build: .
    container_name: tirelire_app
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tirelire
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6
    container_name: tirelire_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
